#!/bin/sh

echo_me() {
	echo $@
	"$@" #previously eval "$@" ... but this works too 
}

echo_me git add -A
echo_me git commit -m "$*" # previously \""$*"\"
echo_me git push origin master 

#ok this works, just now removing quotations to get lo más lean k posible